spring:
  application:
    name: famistry
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 8080

# Docker-specific configuration
logging:
  level:
    '[org.mongodb.driver]': DEBUG
    '[com.famistry]': DEBUG
